import { Sprite, AnimatedSprite } from 'pixi.js';

class Entity {
  constructor(name, x, y, textures, visible = true) {
    this.name = name;
    if (x) {
      this.x = x;
    }

    if (y) {
      this.y = y;
    }

    this.visible = visible;

    if (Array.isArray(textures)) {
      this.animatedSprite = new AnimatedSprite(textures);
    } else if (textures) {
      this.sprite = new Sprite(textures);
    }
  }

  move(x = 0, y = 0) {
    this.x = x;
    this.y = y;
  }

  show() {
    this.visible = true;
  }

  hide() {
    this.visible = false;
  }
}

export default Entity;

    // * General
    //   - Funds/Budget/$
    //   - Field Exp. (aka complete cases to improve this, and receive a "Promotion" or
    //     earn more investment by the guild)
    // * Battle
    //   - Health
    //   - Armor
    //   - Battery
    //   - Actions
    //   - Move
    //   - Vision
    // * Flavor
    //   - Rank
    //   - Class (generated by build/loadout)
